"""
Generic Celery task-status route.

One endpoint serves every background task in the app (exports, bulk
ingest, multi-file report upload) — the frontend polls this with the
task ID it got back from whichever "start X" endpoint it called. Task
IDs are UUIDs generated by Celery and are not guessable, but this route
still requires authentication (not authorization by task owner — see the
note below) since it's still app data flowing through it.

Note on authorization: this endpoint does NOT check that the polling
user is the same user who started the task. Task results only ever
contain data the SUBMITTING user was authorized to see (RBAC is enforced
inside the task itself using the submitting user's identity — see
app/tasks/*.py), so a task ID leaking to a different authenticated user
would expose at most "did this export succeed and here's a signed URL
your colleague already had". If stricter per-task ownership enforcement
is wanted later, add an `owner_user_id` column to a persisted task-audit
table and check it here — deliberately left as a documented simplification
rather than silently pretending it's fully locked down.
"""
from celery.result import AsyncResult
from fastapi import APIRouter, Depends

from app.api.deps import require_any_role
from app.core.celery_app import celery_app
from app.models.user import User
from app.schemas.task import TaskStatusResponse

router = APIRouter(prefix="/tasks", tags=["tasks"])


@router.get("/{task_id}", response_model=TaskStatusResponse)
def get_task_status(
    task_id: str,
    current_user: User = Depends(require_any_role),
):
    result = AsyncResult(task_id, app=celery_app)

    response = TaskStatusResponse(task_id=task_id, status=result.status)

    if result.status == "SUCCESS":
        response.result = result.result
    elif result.status == "FAILURE":
        # str(result.result) is the exception instance Celery captured —
        # never leak a raw traceback to the client, just its message.
        response.error = str(result.result) if result.result else "Task failed."
    elif result.status in ("STARTED", "PENDING", "RETRY"):
        # Custom progress meta set via self.update_state(...) inside a
        # task (see export_tasks.py's "stage" meta) surfaces here if present.
        if isinstance(result.info, dict):
            response.progress = result.info

    return response
