"""changed code to id

Revision ID: 66df86a9ed75
Revises: 0001_initial_schema
Create Date: 2026-08-10 17:52:07.559850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66df86a9ed75'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('sample_id', sa.String(length=150), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'sample_id', name='uq_sample_site_code')
    )
    op.create_index(op.f('ix_samples_is_deleted'), 'samples', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_samples_sample_id'), 'samples', ['sample_id'], unique=False)
    op.create_index(op.f('ix_samples_site_id'), 'samples', ['site_id'], unique=False)
    op.create_index(op.f('ix_samples_subject_id'), 'samples', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'samples', ['sample_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_samples_subject_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_site_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_sample_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_is_deleted'), table_name='samples')
    op.drop_table('samples')
    # ### end Alembic commands ###
