name: Deploy Application

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Deploy application
        run: |
          sudo /usr/local/sbin/inventory-deploy
  
      
