name: Deploy Application

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Test runner
        run: |
          echo "Deployment triggered"
          echo "Running on:"
          hostname
          echo "User:"
          whoami
  
      
